(function() {
    const data = [
        { t: "Kemplezh ar goustiañs denel", h: ["Petra a dermen ar goustiañs : an emskiant, an embrederiadenn, pe un dra bennak muioc'h ?", "Ha produet e vez ar goustiañs gant an argerzhioù biologel pe un dra ziazez eo ?", "Hag an naouegezh artifisiel a c'hallo tizhout ur goustiañs wirion un deiz bennak ?", "Penaos e vez lakaet an dezoù danvezel e diskred gant 'kudenn diaez' ar goustiañs ?", "Pezh liamm zo etre ar goustiañs hag an empenn fizikel ?"] },
        { t: "Hag an 'unan' zo un dra bennak a zizoloer pe a savjer", h: ["Hag un 'unan' lakaet zo o c'hortoz bezañ dizoloet, pe savet e vezoc'h dibaouez gant ho tibaboù hag ar c'henteks ?", "Petra a degouezh gant an identelezh pa cheñch ar c'henteks penn-da-benn — kleñved, divroerezh, koll ?", "Hag an danevell ho peus diwar ho penn zo un dizoloadenn pe ur grouidigezh ?", "Hag-eñ e talvez ar goulenn-mañ evit ho sell war ar vuhez, pe ur goulenn prederouriel rik eo ?", "Ma 'z eo savet an unan, petra eo hor c'harg e sevel ?"] },
        { t: "Gourenerezh an traoù a zibabomp ankounac'haat", h: ["Hag ul liamm moral ho peus gant hoc'h ankounac'hadur deoc'h-unan ?", "Hag ur stumm a zishonestiz gant an unan eo ar memor dibabet ?", "Hag an daskorañ a c'houlenn ankounac'haat, pe ur fazi rumm eo ?", "Petra a ziskouez ur gevredigezh a zibab ankounac'haat a-stroll diwar he fenn ?", "Hag-eñ ez eus eus an amnezia etek — evit an dud pe an vroioù ?"] },
        { t: "Hag ar yezh a stumm ar pezh a c'hallomp soñjal pe hepken ar pezh a c'hallomp lavarout", h: ["Hag-eñ ho peus bet tro da gaout mennozhioù ne oac'h ket evit stummañ en ho yezh kentañ o teskiñ ur yezh all ?", "Hag an dezoù Sapir-Whorf zo ur skeudenn barzhoniel pe ur goulenn epistemologel wirion ?", "Hag-eñ ez eus arnodoù a harz ouzh kement yezh zo ?", "Petra a dalvez klevout un dra bennak ne c'hallit ket envel ?", "Hag ar yezh a implijit en ho monolog diabarzh a cheñch ho sell warnoc'h hoc'h-unan ?"] },
        { t: "Al liamm etre frankiz ha kiriegezh en ho puhez", h: ["Pelec'h en em santit ar frankañ ha petra ho peus paeet evit ar frankiz-se ?", "Hag ar frankiz a vez prenet bepred war goust unan bennak all ?", "Hag-eñ e welit ho kiriegezhioù evel strinkoù pe evel ar pezh a ro ster d'ho frankiz ?", "Hag un den a c'hall bezañ frank da vat hep an amveziadoù danvezel evit lakaat ar frankiz-se e pleustr ?", "Petra e vefec'h prest da goll evit bezañ frankoc'h — ha petra a ziskouez ho respont ?"] },
        { t: "Petra a ra an hiraezh e gwirionez pa zeu d'ho kwelet", h: ["Hag an hiraezh zo glac'har, frealz, distummadur, pe an tri asambles ?", "Hag-eñ ho peus fiziañs en ho santimantoù hiraezhus pe hag-eñ e vezit disfizius outo ?", "Hag ar pezh ho peus hiraezh outañ zo un amzer dremenet wirion pe ur stumm kemmet ?", "Petra a harz an hiraezh ha petra a laka da vezañ posupl ?", "Hag-eñ e c'hall ur gevredigezh bezañ hiraezhus evel un den — ha gant an hevelep dindan-ar-reizhoù ?"] },
        { t: "Hag-eñ e vez lakaet an traoù da vezañ bihanoc'h bepred pa vezont komprenet", h: ["Soñjit en un dra bennak kaer pe gevrinus — hag-eñ e vez lakaet da vezañ nebeutoc'h a se pa vez komprenet ?", "Hag un dalvoudegezh zo gant an nann-ouiziegezh, pe n'eo nemet romantelouriezh ?", "Hag an displegadenn skiantel hag an estlamm estetik a c'hall kenvevañ, pe an eil a laka egile dindan e galloud ?", "Hag-eñ ez eus un dra bennak a wall-virit a gompren dre aon da goll e c'halloud warnoc'h ?", "Petra a ziskouez ar goulenn-mañ diwar-benn harzoù ar rationalouriezh ?"] },
        { t: "An diforc'h etre ho talvoudegezhioù embannet hag ho talvoudegezhioù diskouezet", h: ["Petra a lavar ho tibaboù gwirion — ha n'eo ket ho kredennoù embannet — diwar-benn ar pezh a gont ar muiañ deoc'h ?", "Hag un esaou poanius zo etre an daou ?", "Hag an esaou-se zo ur merk a silidigezh pe ur merk eus an diaezamant wirion da vevañ hervez e bennaennoù ?", "Hag-eñ e c'hallit serriñ an esaou, pe hag-eñ e chom bepred un tamm pellder etre an ideal hag ar gwirvoud ?", "Petra e vefec'h rediet da goll evit lakaat ho puhez muioc'h a-unvan gant ar pezh a lavarit krediñ ennañ ?"] },
        { t: "Hag an onestiz vras zo ur vertuz pe ur stumm a emvlastet", h: ["Hag ar birvilh da 'lavarout an traoù evel m'emaint' zo evit mad an den all pe evit ho tiboan deoc'h-unan ?", "Hag ar vadelezh zo un dibab kalonekoc'h a-wechoù ?", "Pelec'h emañ ar vevenn etre an onestiz hag ar garventez ?", "Hag-eñ e tiskouez ar goulenn evit un onestiz klok en darempredoù an darempred tost pe ar c'hontrol ?", "Hag-eñ e c'hallit soñjal en ur mare m'he deus graet an onestiz vras muioc'h a zroug evit a vad ?"] },
        { t: "Hag an arz meur a rankfe herzel pe frealziñ", h: ["Petra a glaskit e gwirionez pa 'z oc'h gloazet — an diaezamant pe ar frealz ?", "Hag ez eus un arz a zeu a-benn da ober an daou asambles ?", "Hag an arz frealzus zo nebeutoc'h a bouez ennañ evit an arz a laka an den da herzel, pe un diforc'h 'snob' eo ?", "Hag-eñ ez eus ur garg pennañ gant an arz hervezoc'h ?", "Hag-eñ ez eus un oberenn arz he deus ho cheñchet en ur stumm ne vije ket deuet ar frealz a-benn d'ober ?"] },
        { t: "Ar goulenn evit ar c'hempouez ha hag-eñ e ro ur wirionez faos", h: ["Hag-eñ 'prouiñ an daou du' zo reizh bepred, pe hag-eñ e c'hall distummañ ar wirionez ?", "Hag un diforc'h zo etre kempouez ha kevatalder faos ?", "Piv a zibab pe stumm a virit bezañ klevet ?", "Hag ar c'hempouez kazetenner a c'hall kenvevañ gant reolennoù epistemel ?", "Petra eo koust reiñ ur gador d'ur sav-poent en anv ar reizhded ?"] },
        { t: "Hag an araokadenn moral zo wirion pe un doare giz moral hepken", h: ["Hag hor fiziañs etek hiziv zo ur merk a araokadenn wirion pe an hevelep proviñselouriezh gant dilhad nevez ?", "Petra a dalvezfe e vije gwirion an araokadenn moral ?", "Hag-eñ e c'hallit soñjal en un dra bennak a gredomp ennañ hiziv ha m'o devo mezh ar remziadoù da zont o sellout outañ ?", "Hag-eñ e laka perzh relativedel ar c'hiz moral en arvar ar mennozh e vefe un dra bennak fall e gwirionez ?", "Hag an uvelded moral zo kenglotus gant ar gredenn moral ?"] },
        { t: "Lodennoù ac'hanoc'h hoc'h-unan ho peus an diaesañ da ezteuler", h: ["Hag ez eus un dra bennak a santit met ne c'hallit ket kavout gerioù evitañ ?", "Hag an diaezamant zo gant ar yezh pe gant an dra e-unan ?", "Hag-eñ e soñjit ez eus arnodoù diabarzh hag a zo prevez da vat — ne c'hallit ket zoken tizhout hoc'h-unan ?", "Petra a dalvezfe kompren ho tiabarzh penn-da-benn ?", "Hag-eñ eo ret anezteuladenn evit ma vefe wirion ?"] },
        { t: "Heuliadoù politikel ar gwalc'h", h: ["Hag-eñ eo ur mank moral bezañ gwalc'het e gwirionez en ur bed direizh ?", "Hag-eñ eo kenglotus klask ar peoc'h personel gant ur goustiañs politikel ?", "Hag ar gapitalouriezh a denn gounid eus ur boblañs walc'het ?", "Hag-eñ ez eus ur stumm a walc'h ha n'eo ket sioulder politikel ?", "Penaos e merreoc'h hoc'h-unan an esaou etre ar peoc'h diabarzh hag an emouestl diavaez ?"] },
        { t: "Memor, identelezh, ha petra a chom pa vez kemmet an eil hag egile", h: ["Ma vije kemmet ho memorioù e stumm ur reizhiad, hag-eñ e vefec'h c'hoazh ac'hanoc'h hoc'h-unan ?", "Petra eo kendalc'husted an unan e gwirionez ?", "Hag an den ho peus memor anezhañ zo an hevelep den hag an hini a gomz bremañ ?", "Petra a degouezh gant an identelezh en arnoded ar c'holl pe ar cheñchamant bras ?", "Hag-eñ eo m'eus goulenn an identelezh personel evit ar stumm ma vez graet an eil ouzh egile — war an dachenn lezennel, etek ?"] },
        { t: "Hag-eñ e talvez bepred ar boan bevañ ur vuhez prederiet", h: ["Sokrates a lavare ne dalveze ket ar boan bevañ ur vuhez hep preder — hag a-du oc'h ?", "Hag-eñ ez eus ur c'houst d'ar preder — ur stumm a baralizenn pe ur c'holl a beurelezh ?", "Hag-eñ e c'hall ar preder dont da vezañ ur stumm d'en em zivizout ?", "Hag-eñ ez eus tud hag a vev don ha mat hep kalz a breder warno o-unan ?", "Petra ho peus kollet ha gounezet hervezoc'h gant ho live preder warnoc'h hoc'h-unan ?"] },
        { t: "Goulenn ar pezh a dleit d'an dud dianav", h: ["Hag-eñ ho peus dleadennoù d'an dud ne gejet biken outo ?", "Betek pelec'h ez a ho tleadennoù moral — d'ho karter, d'ho pro, d'ar bed ?", "Hag-eñ e vez bihanaet an dlead gant an esaou fizikel pe sevenadurel, pe un doare d'en em zifenn eo ?", "Petra eo an diforc'h etre an aluzen hag ar reizhded ?", "Penaos e vevit e gwirionez e-keñver ar goulenn-mañ ?"] },
        { t: "An istorioù a lavar ar sevenadurioù diwar o fenn", h: ["Pep kevredigezh he deus ur vojenn diazez — petra eo ho hini, ha betek pelec'h eo gwirion ?", "Petra a zibab ur vroad ankounac'haat kement hag ar pezh a zibab kounaat ?", "Hag an identelezh vroadel zo ur grouidigezh talvoudus pe un dra dangereus ?", "Hag-eñ e c'hall ur gevredigezh kaout un danevell onestoc'h diwar he fenn hep koll he liamm ?", "Pezh istor a lavarfec'h diwar-benn ho sevenadur ma tlefec'h bezañ onest penn-da-benn ?"] },
        { t: "Hag-eñ e c'hall kement skrid zo bezañ troet penn-da-benn", h: ["Hag-eñ ho peus arnoded un dra bennak en ur yezh all hag a harze ouzh an droidigezh ?", "Hag an neptraduzidigezh eus gerioù zo zo ur prouenn e stumm ar yezh ar soñj ?", "Petra a gollomp ha petra a c'hounezomp en droidigezh ?", "Hag un droidigezh dispar zo ur stumm a grouidigezh pe ur stumm a goll ?", "Petra a lavar an droidigezh deomp diwar-benn harzoù ar c'hompren etre ar sevenadurioù ?"] },
        { t: "Arnoded an dalc'h traoù enebet evel gwirion asambles", h: ["Hag-eñ e c'hallit karout unan bennak ha kaout droug outañ asambles hep ma vefe nullet an eil gant egile ?", "Hag-eñ eo ar barregezh da zerc'hel an enebadur ur merk a maturelezh pe ur merk a gemmesk ?", "Hag-eñ ez eus sav-poentoù politikel pe moral ho peus hag a zo en emgann e gwirionez ?", "Hag ar goulenn evit ar c'henglotusted en hor c'hredennoù a ziskouez ar rationalouriezh pe ar reterezh ?", "Petra eo an dra a gredit ennañ hag a ya a-enep un dra all a gredit ennañ ivez ?"] },
        { t: "Petra a dalvez ne viot ket mui un deiz bennak", h: ["Hag-eñ e soñjit en ho marvelezh deoc'h-unan alies, a-wechoù, pe tost biken ?", "Hag an emskiant eus ar marv he deus stummet ho stumm da vevañ pe ar pezh a dalv deoc'h ?", "Hag aon rak ar marv zo rational, pe ur c'hemmesk eo diwar-benn ar pezh a vez kollet ?", "Hag-eñ e kavit frealz en ur stumm bennak da soñjal er marvelezh ?", "Petra a laka ar marvelezh da vezañ posupl ha na vije ket lakaet gant an divarvelezh marteze ?"] }
    ];
    const lang = "br";
    if (!window.speakingData) window.speakingData = {};
    if (!window.speakingData[lang]) window.speakingData[lang] = {};
    if (!window.speakingData[lang]["talkThatTalk"]) window.speakingData[lang]["talkThatTalk"] = [];
    window.speakingData[lang]["talkThatTalk"].push(...data);
})();