(function() {
    const data = [
        { t: "An unan n'eo ket un dra a zizoloer — un dra a grouer bepred eo.", tag: "Identelezh & Prederouriezh", h: ["Hag-eñ e santit ar mennozh-mañ evel un dra a zieub ac'hanoc'h pe a laka ac'hanoc'h da goll ho kempouez ?", "Petra a dalvezfe evit ho tibaboù ma vije an identelezh savet e-lec'h bezañ kavet ?", "Hag ez eus un dra bennak a santit evel un 'unan' stag ha pennañ ?", "Hag an unan a ziskouezit d'ar re all a stumm an unan a zeuit da vezañ ?", "Petra a zegouezh gant an identelezh en arnoded ar c'holl pe ar cheñchamant bras ?"] },
        { t: "Ar drugarez a c'houlenn un istor eeun n'eo ket drugarez wirion — sentimentalouriezh eo.", tag: "Etek", h: ["Hag un diforc'h zo etre an drugarez wirion hag an emzalc'h santimantel ouzh un istor bamus ?", "Hag-eñ e c'hallit soñjal en un degouezh m'he deus un istor eeunaet distummet ar gwirvoud ?", "Hag ar sentimentalouriezh a laka ac'hanomp da santout emaomp oc'h ober un dra bennak pa n'emaomp ket ?", "Hag-eñ eo ret an eeunadur evit an emskiant ?", "Petra eo koust bihanaat ar boan d'un danevell aes da gompren ?"] },
        { t: "Kement ideologiezh, lakaet da benn he poell, a zeu da vezañ ur stumm a feulster.", tag: "Prederouriezh Politikel", h: ["Hag-eñ e c'hallit soñjal en un ideologiezh a dec'h rak ar boell-mañ ?", "Hag un abeg eo evit nac'hañ an ideologiezh penn-da-benn pe evit he dougen gant skañvded ?", "Petra eo an diforc'h etre ur sav-poent a bennaenn hag un ideologiezh ?", "Hag ar bratikelezh a dec'h rak an trap-mañ pe hag e guzhat a ra ?", "Hag-eñ e talvez kement-mañ e vefe kement sav-poent politikel zo ken dangeros an eil hag egile ?"] },
        { t: "Ar yezh ne zeskriv ket ar gwirvoud — e sevel a ra.", tag: "Yezhouriezh & Prederouriezh", h: ["Hag-eñ ho peus bet tro da gaout mennozhioù ne oac'h ket evit stummañ en ho yezh kentañ o teskiñ ur yezh all ?", "Hag un dra bennak a santit ne c'hall yezh ebet envel ?", "Hag ar yezh a implijit evit soñjal a cheñch ho santimantoù ?", "Hag-eñ eo posupl kaout ur mennozh hep ger ebet evitañ ?", "Petra a dalvez kement-mañ evit an droidigezh — hag-eñ e c'hall ur mennozh bezañ troet penn-da-benn ?"] },
        { t: "An dra dispackeroc'h a c'hall un den ober er bed modern eo bezañ gwalc'het a-greiz-kalon.", tag: "Kevredigezh", h: ["Hag ar gwalc'h zo politikel ?", "Hag an ekonomiezh he deus ezhomm eus bevezerien digwalc'h ?", "Hag ar gwalc'h gwirion zo posupl zoken pe un istor a lavaromp deomp hon-unan eo ?", "Hag un diforc'h zo etre ar gwalc'h hag an daskorañ ?", "Hag-eñ e talvez bezañ gwalc'het n'ho peus ket ken a nann-onestiz ouzh ar bed ?"] },
        { t: "Ar goulenn evit ar c'hempouez er gaoz foran a ro alies ur wirionez faos da sav-poentoù ne veritont ket anezhi.", tag: "Mediaoù & Epistemologiezh", h: ["Hag-eñ 'prouiñ an daou du' zo reizh bepred, pe hag-eñ e c'hall distummañ ar wirionez ?", "Piv a zibab pe stumm a virit bezañ klevet ?", "Hag un diforc'h zo etre kempouez ha kevatalder faos ?", "Hag ar c'hempouez kazetenner a c'hall kenvevañ gant reolennoù epistemel ?", "Petra eo koust reiñ ur gador d'ur sav-poent en anv ar reizhded ?"] },
        { t: "An onestiz vras, hep furnez, n'eo nemet garventez gant mennozhioù mat.", tag: "Etek", h: ["Hag ar birvilh da 'lavarout an traoù evel m'emaint' zo evit mad an den all pe evit ho tiboan deoc'h-unan ?", "Hag-eñ e c'hallit soñjal en ur mare m'he deus graet an onestiz vras ur gaou wirion ?", "Hag ar vadelezh zo un dibab kalonekoc'h a-wechoù ?", "Pelec'h emañ ar vevenn etre an onestiz hag ar garventez ?", "Hag-eñ e tiskouez ar goulenn evit un onestiz klok en darempredoù an darempred tost pe ar c'hontrol ?"] },
        { t: "Ar frankiz a youl zo ur grouidigezh ret muioc'h evit ur gwirvoud a ster.", tag: "Prederouriezh", h: ["Hag-eñ e talvez un dra bennak e vefe gwirvoudel ma rankomp ober evel pa vije ?", "Petra e vefe ar giriegezh moral en ur bed hep frankiz a youl ?", "Hag ar skiantoù an empenn a diskoulm ar goulenn pe hag e lakaat a reont en ur stumm all ?", "Hag ar gredenn er frankiz a youl zo ur produ eus un argerzh rakstummet ?", "Petra a lavar ho spered deoc'h — ha fiziañs ho peus ennañ diwar-benn ar goulenn-mañ ?"] },
        { t: "An internet n'en deus ket lakaet ac'hanomp da vezañ muioc'h titouret — lakaet en deus ac'hanomp da vezañ muioc'h sur eus hor fazioù.", tag: "Teknologiezh & Epistemologiezh", h: ["Hag-eñ e c'hallit soñjal en ur gredenn ho poa hag a zo bet stummet gant algoritmoù ?", "Hag an internet eo ar gudenn pe natur an den o kemmañ gantañ ?", "Pezh pratik epistemel a warez diouzh kement-mañ ?", "Hag-eñ eo an ampartiz un dra a ster c'hoazh d'ur mare ma c'hall kement den zo embann traoù ?", "Fiziañs ho peus en ho parregezh da lakaat un talvoudegezh d'an titouroù war an internet ?"] },
        { t: "An arz a frealz zo nebeutoc'h a dalvoudegezh ennañ evit an arz a laka an den da herzel.", tag: "Estetik", h: ["Hag-eñ e c'hallit soñjal en un arz en deus graet an daou asambles ?", "Hag un urzhaz eus an talvoudegezhioù arz zo, pe hag ur snobelezh eo ?", "Petra a glaskit e gwirionez pa 'z oc'h gloazet — an diaezamant pe ar frealz ?", "Hag an arz a laka an den da herzel a cheñch an emzalc'h pe ar santimant hepken ?", "Petra eo pal an arz — herzel, prederiañ pe treizhañ ?"] },
        { t: "An araokadenn moral zo wirion, met ar mennozh e kerzh an istor en ur roud eo ur vojenn.", tag: "Istor & Prederouriezh", h: ["Hag-eñ e c'hallit soñjal en un dra degemeret hiziv hag a ziskouez un araokadenn moral wirion ?", "Hag-eñ e c'hallit soñjal en un dra hon deus kollet ?", "Hag ar gredenn en araokadenn moral zo ur mennozh sevenadurel dibar ?", "Hag ar c'hiz moral a vez kemmesket gant an araokadenn moral ?", "Petra eo ho prouenn omp gwelloc'h evit ar remziadoù kent ?"] },
        { t: "Klask ar c'hredusted eo gwrizienn ar muiañ a garventez denel.", tag: "Prederouriezh", h: ["Hag-eñ e c'hallit soñjal en un istor pe en un dra personel m'he deus an ezhomm a gredusted graet droug ?", "Hag an douetañs zo ur vertuz moral ?", "Hag an dud gant kredennoù kreñv a laka ar bed da vezañ gwelloc'h pe washoc'h ?", "Hag ez eus ur stumm a gredusted n'eo ket dangereus ?", "Penaos dougen kredennoù kreñv hep bezañ reut ?"] },
        { t: "Ar memor n'eo ket un enrolladur eus ar pezh a zo c'hoarvezet — un istor a adskrivomp bepred eo.", tag: "Psikologiezh", h: ["Hag ur memor deoc'h zo bet lakaet e rann ar marteze gant un den a oa eno ?", "Hag-eñ e soñjit e cheñchomp hor memorioù evit gwareziñ ur skeudenn ac'hanomp hon-unan ?", "Petra a dalvez kement-mañ evit an identelezh personel — hag-eñ oc'h an den ho peus koun anezhañ ?", "Hag-eñ e c'hall ur memor adskrivet bezañ muioc'h gwirion evit an darvoud kentañ ?", "Petra eo ar memor kreñvañ ho peus, ha pegen sur oc'h anezhañ e gwirionez ?"] },
        { t: "N'eus ket a veveziñ etek dindan ar gapitalouriezh ziwezhat — hag ur rann evit ober eo, ha n'eo ket evit daskoriñ.", tag: "Etek", h: ["Hag-eñ e soñjit e talvez dibaboù ar vevezerien ?", "Hag ar stumm m'eo diskouezet ar cheñchamant hin hag ar gwall-implij evel ur giriegezh personel zo ur mennozh politikel a-ratozh ?", "Petra eo an diforc'h etre ar cheñchamant reizhiad hag an oberenn unan ?", "Hag-eñ eo posupl bevañ en ur stumm etek en ur reizhiad nann-etek ?", "Hag an anaoudegezh eus an dibosublusted a veveziñ etek a cheñch ho stumm d'en em zerc'hel ?"] },
        { t: "Ar vuhez prederiet a dalias bevañ — met he frediñ re dost a c'hall he lakaat da vezañ divevuz.", tag: "Prederouriezh", h: ["Pegen a breder warnoc'h hoc'h-unan zo re ?", "Hag-eñ e c'hall ar preder dont da vezañ ur stumm d'en em zivizout ?", "Hag-eñ ez eus ur c'houst d'ar preder warnoc'h hoc'h-unan bepred ?", "Hag-eñ ez eus tud hag a vev don ha mat hep kalz a breder warno o-unan ?", "Petra ho peus kollet ha gounezet hervezoc'h gant ho live preder warnoc'h hoc'h-unan ?"] },
        { t: "Etek an drevadennerezh war blanedennoù all.", tag: "Etek & Egorenn", h: ["Hag ur gwir hon eus da gemer bedoù all pa n'hon deus ket diskoulmet kudennoù hor bed ?", "Hag-eñ e rankfemp kas reizhiadoù denel (kapitalouriezh, broadelouriezh) d'an egorenn ?", "Petra eo hor dleadennoù moral ouzh ur vuhez all marteze, zoken ma 'z eo mikrobennel ?", "Hag ar mennozh 'Steuñv B' zo un dra dangereus evit ar gwareziñ ekologel war an Douar ?", "Piv a rankfe kaout pe ren ar pinvidigezhioù planetel ?"] },
        { t: "Hag ar frankiz a youl zo anezhi e gwirionez pe hag ur skeud eo ?", tag: "Prederouriezh", h: ["Ma 'z eo hon oberoù rakstummet, hag-eñ omp kiriek ?", "Hag ar santimant a zibab zo a-walc'h evit prouiñ ar frankiz a youl ?", "Hag un urzhiataer ampart a c'hallfe rakwelout kement dibab ho peus d'ober ?", "Petra eo an diforc'h etre 'frankiz diouzh' ha 'frankiz evit' ?", "Hag an ene pe an emskiant a cheñch ar goulenn ?"] }
    ];
    const lang = "br";
    if (!window.speakingData) window.speakingData = {};
    if (!window.speakingData[lang]) window.speakingData[lang] = {};
    if (!window.speakingData[lang]["opinions"]) window.speakingData[lang]["opinions"] = [];
    window.speakingData[lang]["opinions"].push(...data);
})();
