(function() {
    const lang = "br";
    const data = [
        {"topic": "Kafe pe te: pezh evaj d'ar beure zo gwelloc'h?", "sideA": "Kafe", "sideB": "Te", "level": "starter", "theme": "food_drink", "ideasA": ["Energiezh", "C'hwezh mat"], "ideasB": ["Yac'h", "Diskuizh"]},
        {"topic": "Preti pe keginañ er gêr: pezh zo gwelloc'h?", "sideA": "Preti", "sideB": "Keginañ er gêr", "level": "starter", "theme": "food_drink", "ideasA": ["Lestri ebet da walc'hiñ", "Keginerien a-vicher"], "ideasB": ["Marc'hadmatoc'h", "Yac'hoc'h"]},
        {"topic": "Hañv pe goañv: pe vare-bloaz zo gwelloc'h?", "sideA": "Hañv", "sideB": "Goañv", "level": "starter", "theme": "time", "ideasA": ["Heol", "Traezhenn"], "ideasB": ["Erc'h", "Ski"]},
        {"topic": "Levr pe film: pezh zo gwelloc'h?", "sideA": "Levr", "sideB": "Film", "level": "starter", "theme": "social", "ideasA": ["Imajinañ", "Deskiñ kalz traoù"], "ideasB": ["Prim", "Gwelet gant mignoned"]},
        {"topic": "Marc'h-houarn pe karr: pezh zo gwelloc'h evit ar gêr?", "sideA": "Marc'h-houarn", "sideB": "Karr", "level": "starter", "theme": "travel", "ideasA": ["Mat evit ar c'horf", "Gratis"], "ideasB": ["Prim-tre", "Tomm pa vez glav"]},
        {"topic": "Pizza pe burger: pezh zo gwelloc'h?", "sideA": "Pizza", "sideB": "Burger", "level": "starter", "theme": "food_drink", "ideasA": ["Rannañ", "Kalz keuz"], "ideasB": ["Aes da zebriñ", "Mat gant patatez frit"]},
        {"topic": "Kêr pe maez: pe lec'h zo gwelloc'h evit bevañ?", "sideA": "Kêr", "sideB": "Maez", "level": "starter", "theme": "furniture", "ideasA": ["Kalz stalioù", "Mont er-maez diouzh an noz"], "ideasB": ["Sioul-tre", "Aer yac'h"]},
        {"topic": "Beure pe noz: pe lodenn eus an deiz zo gwelloc'h?", "sideA": "Beure", "sideB": "Noz", "level": "starter", "theme": "time", "ideasA": ["Energiezh", "Heol o sevel"], "ideasB": ["Diskuizhañ", "Gwelet filmoù"]},
        {"topic": "Tramig pe karr-nij: pezh zo gwelloc'h evit beajiñ?", "sideA": "Tramig", "sideB": "Karr-nij", "level": "starter", "theme": "travel", "ideasA": ["Gwelet an dremmvro", "Gwelloc'h evit an natur"], "ideasB": ["Prim-tre", "Mont pell-tre"]},
        {"topic": "Mor pe menezioù: pezh zo gwelloc'h evit an vakañsoù?", "sideA": "Mor", "sideB": "Menezioù", "level": "starter", "theme": "travel", "ideasA": ["Neuial", "Heol"], "ideasB": ["Bale", "Brav"]},
        {"topic": "Labourat e-unan pe gant ur strollad: pezh zo gwelloc'h?", "sideA": "E-unan", "sideB": "Strollad", "level": "starter", "theme": "work", "ideasA": ["Selaou muioc'h", "Mont primoc'h"], "ideasB": ["Muioc'h a soñjoù", "Dudi muioc'h"]},
        {"topic": "Galv pe kemennadenn: pezh zo gwelloc'h?", "sideA": "Galv", "sideB": "Kemennadenn", "level": "starter", "theme": "technology", "ideasA": ["Selaou ar vouezh", "Primoc'h"], "ideasB": ["Soñjal a-raok skrivañ", "Responti diwezhatoc'h"]},
        {"topic": "Dilhad aes pe dilhad brav: pezh zo gwelloc'h?", "sideA": "Aes", "sideB": "Brav", "level": "starter", "theme": "clothes", "ideasA": ["Bezañ mat", "Praktik"], "ideasB": ["Brav-tre", "Mat evit al labour"]},
        {"topic": "Sukr pe holen: pezh zo pouezusoc'h?", "sideA": "Sukr", "sideB": "Holen", "level": "starter", "theme": "food_drink", "ideasA": ["Evit an dibenn-pred", "An holl a gar ar chokolad"], "ideasB": ["Evit ar pred", "Blaz mat"]},
        {"topic": "Fest bras pe koan vihan: pezh zo gwelloc'h?", "sideA": "Fest bras", "sideB": "Koan vihan", "level": "starter", "theme": "social", "ideasA": ["Kejañ gant tud nevez", "Sonerezh kreñv"], "ideasB": ["Kaozeal sioul", "Sioul eo"]},
        {"topic": "Ti pe ranndi: pe lec'h zo gwelloc'h evit bevañ?", "sideA": "Ti", "sideB": "Ranndi", "level": "starter", "theme": "furniture", "ideasA": ["Liorzh", "Plas"], "ideasB": ["Marc'hadmat", "Aes da naetaat"]},
        {"topic": "Arc'hant pe amzer vak: pezh zo pouezusoc'h?", "sideA": "Arc'hant", "sideB": "Amzer vak", "level": "starter", "theme": "life", "ideasA": ["Prenañ traoù", "Surentez"], "ideasB": ["Plijadur ar vuhez", "Lle soursi"]},
        {"topic": "Chokolad du pe chokolad gant laezh: pezh zo gwelloc'h?", "sideA": "Du", "sideB": "Laezh", "level": "starter", "theme": "food_drink", "ideasA": ["Mat evit ar galon", "Lle sukr"], "ideasB": ["Tamm sukret", "Mat gant kafe"]},
        {"topic": "Sinema pe Netflix er gêr: pezh zo gwelloc'h?", "sideA": "Sinema", "sideB": "Netflix", "level": "starter", "theme": "social", "ideasA": ["Skramm bras", "Son dispar"], "ideasB": ["Aes oc'h", "Paouez ar film"]},
        {"topic": "Beajiñ e-unan pe gant mignoned: pezh zo gwelloc'h?", "sideA": "E-unan", "sideB": "Mignoned", "level": "starter", "theme": "travel", "ideasA": ["Dibab pep tra", "Kejañ gant muioc'h a dud"], "ideasB": ["Rannañ eñvorennoù", "Marc'hadmatoc'h"]},
        {"topic": "Podkastoù pe sonerezh: pezh zo gwelloc'h er c'harr?", "sideA": "Podkast", "sideB": "Sonerezh", "level": "starter", "theme": "social", "ideasA": ["Deskiñ traoù", "Istorioù dedennus"], "ideasB": ["Kanañ", "Energiezh"]},
        {"topic": "Glav pe avel: pezh zo gwashoc'h?", "sideA": "Glav", "sideB": "Avel", "level": "starter", "theme": "nature", "ideasA": ["Gleb eo pep tra", "Trist eo an amzer"], "ideasB": ["Yen eo", "Drouk evit ar blev"]},
        {"topic": "Donezon dic'hortoz pe dibab an donezon: pezh zo gwelloc'h?", "sideA": "Dic'hortoz", "sideB": "Dibab", "level": "starter", "theme": "social", "ideasA": ["From kreñv", "Mad eo"], "ideasB": ["Kaout pezh ho peus c'hoant", "Donezon fall ebet"]},
        {"topic": "Skrivañ war baper pe war un dabletenn: pezh zo gwelloc'h?", "sideA": "Paper", "sideB": "Tabletenn", "level": "starter", "theme": "technology", "ideasA": ["Batri ebet", "Santimant mat"], "ideasB": ["Prim", "Mirout paper"]},
        {"topic": "Sandwich pe saladenn: pezh zo gwelloc'h evit koan?", "sideA": "Sandwich", "sideB": "Saladenn", "level": "starter", "theme": "food_drink", "ideasA": ["Aes da gas", "Kof leun"], "ideasB": ["Boued skañv", "Kalz vitaminoù"]},
        {"topic": "Leti pe camping: pezh zo gwelloc'h evit an vakañsoù?", "sideA": "Leti", "sideB": "Camping", "level": "starter", "theme": "travel", "ideasA": ["Aesoc'h", "Lein zo"], "ideasB": ["En natur", "Un avantur eo"]},
        {"topic": "Komz pe selaou: pezh zo pouezusoc'h?", "sideA": "Komz", "sideB": "Selaou", "level": "starter", "theme": "work", "ideasA": ["Rannañ soñjoù", "Pouezus evit ar rener"], "ideasB": ["Deskiñ gant ar re all", "Mad eo"]},
        {"topic": "Nevez-amzer pe diskar-amzer: pezh zo gwelloc'h?", "sideA": "Nevez-amzer", "sideB": "Diskar-amzer", "level": "starter", "theme": "time", "ideasA": ["Bleunioù o kreskiñ", "Amzer dommoc'h"], "ideasB": ["Delioù brav", "Plijus evit bale"]},
        {"topic": "Frouezh pe legumaj: pezh zo gwelloc'h?", "sideA": "Frouezh", "sideB": "Legumaj", "level": "starter", "theme": "food_drink", "ideasA": ["Tamm sukret", "Mat evit kignat"], "ideasB": ["Yac'h-tre", "Mat evit keginat"]},
        {"topic": "Filmoù ober pe fent: pezh zo gwelloc'h?", "sideA": "Ober", "sideB": "Fent", "level": "starter", "theme": "social", "ideasA": ["Dudius ha prim", "Efedoù brav"], "ideasB": ["C'hoarzhin", "Mat evit diskuizhañ"]},
        {"topic": "Gwalc'hiñ al lestri pe naetaat gant an aspirer: pezh zo gwelloc'h?", "sideA": "Lestri", "sideB": "Aspirer", "level": "starter", "theme": "furniture", "ideasA": ["Dour tomm zo mat", "Labour sioul"], "ideasB": ["Prim eo", "Gwelet an disoc'h diouzhtu"]},
        {"topic": "Sonerezh pop pe rock: pezh zo gwelloc'h?", "sideA": "Pop", "sideB": "Rock", "level": "starter", "theme": "social", "ideasA": ["Kanaouennoù brav", "Mat evit dañsal"], "ideasB": ["Binvioù-seniñ dispar", "Energiezh kreñv"]},
        {"topic": "Abred pe diwezhat: pezh zo gwelloc'h?", "sideA": "Abred", "sideB": "Diwezhat", "level": "starter", "theme": "time", "ideasA": ["Beure sioul", "Devezh mat"], "ideasB": ["Imajinañ diouzh an noz", "Kousket diwezhat"]},
        {"topic": "Bale pe redek: pezh zo gwelloc'h?", "sideA": "Bale", "sideB": "Redek", "level": "starter", "theme": "health", "ideasA": ["Diskuizhañ", "Gwelet an natur"], "ideasB": ["Mat evit ar galon", "Prim-tre"]},
        {"topic": "Urzhiataer hezoug pe unan burev: pezh zo gwelloc'h?", "sideA": "Hezoug", "sideB": "Burev", "level": "starter", "theme": "technology", "ideasA": ["Kas anezhañ e pep lec'h", "Labourat e pep lec'h"], "ideasB": ["Skramm brasoc'h", "Kreñvoc'h"]},
        {"topic": "Treuzdougen stroll pe taksi: pezh zo gwelloc'h?", "sideA": "Karr-boutin/Tramig", "sideB": "Taksi", "level": "starter", "theme": "travel", "ideasA": ["Marc'hadmatoc'h", "Gwelloc'h evit an natur"], "ideasB": ["Diouzhtu d'an ti", "Aesoc'h"]},
        {"topic": "Skornenn pe wastell: pezh zo gwelloc'h evit an dibenn-pred?", "sideA": "Skornenn", "sideB": "Wastell", "level": "starter", "theme": "food_drink", "ideasA": ["Yen", "Fresk"], "ideasB": ["Tomm", "Deiz-ha-bloaz"]},
        {"topic": "Email pe lizher: pezh zo gwelloc'h?", "sideA": "Email", "sideB": "Lizher", "level": "starter", "theme": "technology", "ideasA": ["Prim-tre", "Gratis"], "ideasB": ["Personneloc'h", "Brav da virout"]},
        {"topic": "Traezhenn pe park: pezh zo gwelloc'h?", "sideA": "Traezhenn", "sideB": "Park", "level": "starter", "theme": "nature", "ideasA": ["Neuial", "C'hoari gant an traezh"], "ideasB": ["Gwez ha disheol", "Mat evit piknikañ"]},
        {"topic": "Keginat pe naetaat: pezh zo gwelloc'h?", "sideA": "Keginat", "sideB": "Naetaat", "level": "starter", "theme": "furniture", "ideasA": ["Imajinañ", "Boued mat"], "ideasB": ["Ti kempenn", "Labour sioul"]},
        {"topic": "Vakañsoù berr pe vakañsoù hir: pezh zo gwelloc'h?", "sideA": "Berr", "sideB": "Hir", "level": "starter", "theme": "travel", "ideasA": ["Aes da aozañ", "Kalz beajoù"], "ideasB": ["Diskuizhañ muioc'h", "Gwelet muioc'h"]},
        {"topic": "Faltazi pe get: pezh zo gwelloc'h?", "sideA": "Faltazi", "sideB": "Get", "level": "starter", "theme": "social", "ideasA": ["Istorioù dudius", "Tec'hel kuit"], "ideasB": ["Deskiñ traoù", "Keleier ar bed"]}
    ];
    if (!window.speakingData) window.speakingData = {};
    if (!window.speakingData[lang]) window.speakingData[lang] = {};
    if (!window.speakingData[lang]["debates"]) window.speakingData[lang]["debates"] = [];
    window.speakingData[lang]["debates"].push(...data);
})();
