#!/usr/bin/env python3
"""
COSYmanuals Raw Teacher Notes Check Script
-------------------------------------------
Verifies that lesson HTML files generated by `scripts/extract_manuals.py`
do not contain raw unparsed teacher_notes dumps such as `code: "`, `pronunciation: [{`, or `&quot;point&quot;`.
Exits with code 0 if clean, or code 1 if forbidden patterns are found.
"""

import json
import sys
from pathlib import Path

FORBIDDEN_PATTERNS = [
    'pronunciation: [{',
    'code: "',
    '&quot;point&quot;'
]

def check_file(path):
    content = path.read_text(encoding='utf-8', errors='ignore')
    violations = []
    for pattern in FORBIDDEN_PATTERNS:
        if pattern in content:
            violations.append(pattern)
    return violations

def get_extracted_manual_dirs():
    curriculum_base = Path("curriculums")
    json_files = list(curriculum_base.glob("**/*.json"))
    valid_files = [f for f in json_files if "_schema" not in str(f) and "_archive" not in str(f)]

    dirs = set()
    for f in valid_files:
        try:
            with open(f, 'r', encoding='utf-8') as fh:
                data = json.load(fh)
            if isinstance(data, dict):
                lang = data.get("language")
                course_type = data.get("course_type")
                level = data.get("level")
                if lang and course_type and level and "units" in data:
                    out_dir = Path("manuals") / str(lang).lower() / str(course_type).lower() / str(level).lower()
                    dirs.add(out_dir)
        except Exception:
            pass
    return dirs

def main():
    extracted_dirs = get_extracted_manual_dirs()
    if not extracted_dirs:
        print("No active curriculum files found feeding extract_manuals.py.")
        sys.exit(0)

    html_files = []
    for d in extracted_dirs:
        if d.exists():
            html_files.extend(d.glob("*.html"))

    print(f"Scanning {len(html_files)} generated manual HTML files across {len(extracted_dirs)} extracted directories...")

    failures = {}
    for html_file in html_files:
        violations = check_file(html_file)
        if violations:
            failures[str(html_file)] = violations

    if failures:
        print(f"\n❌ FAIL: Found raw teacher_notes dumps in {len(failures)} generated HTML files:")
        for filepath, patterns in failures.items():
            print(f"  - {filepath}: contains {', '.join(patterns)}")
        sys.exit(1)
    else:
        print("\n✅ PASS: All generated manual HTML files are free of raw teacher_notes dumps.")
        sys.exit(0)

if __name__ == "__main__":
    main()
